### ISSUE TITLE
Hello, God, let me ask you a question,

### ISSUE THREAD

**Issue by WangYiOS** [Mixpeal/flutter_paypal#18]
Hello, God, let me ask you a question,

Does this library only support USD currency? USD needs to be calculated by itself and passed into the code, can't it be calculated automatically? For example, RMB will be converted into USD. I hope the Great God can reply to me。

`
"amount": {
      "total": '10.12',
      "currency": "USD",
      "details": {
        "subtotal": '10.12',
        "shipping": '0',
        "shipping_discount": 0
      }
    },
`

=======

你好，大神，我问一个问题， 

这个库只支持使用USD货币吗？USD需要自己计算传递到代码中，不能自动计算吗？比如人民币转为USD,希望大神能回复我一下

**Comment by Mixpeal** [comment]
Quick one: It seems your translation is off, you should try GPT tools (like BrassGPT) next time, seems more accurate

About your question, I haven't tried other currencies with it, you should use the RMB and supply the actual RMB amount to it.

let me know if it works.

**Comment by WangYiOS** [comment]
> Quick one: It seems your translation is off, you should try GPT tools (like BrassGPT) next time, seems more accurate
> 
> About your question, I haven't tried other currencies with it, you should use the RMB and supply the actual RMB amount to it.
> 
> let me know if it works.

Thank you for replying to me. Now I have solved the currency conversion problem, and the background developer has helped me return USD. Thank you for this, and wish you a good day
