### ISSUE TITLE
validation error

### ISSUE THREAD

**Issue by hamzali4642** [Mixpeal/flutter_paypal#2]
onError: {name: VALIDATION_ERROR, message: Invalid request - see details, debug_id: 1b85ada0b83db, information_link: https://developer.paypal.com/docs/api/payments/#errors, details: [{field: note_to_payer, location: body, issue: Value too long (max length 165)}]}

**Comment by Mixpeal** [comment]
The note field, how long is it?

**Comment by hamzali4642** [comment]
It was empty before, now I add a note, now its working perfectly.

**Comment by Mixpeal** [comment]
@hamzali4642 , nice
