### ISSUE TITLE
Application rejected by google play when I integrated this plugin

### ISSUE THREAD

**Issue by belaidaitzeggane** [Mixpeal/flutter_paypal#4]
my application was working correctly on google play ;
when I try to update with this plugin I get this error : 

```
We found that your app is using Tencent TBS SDK which contains code to download executable code (e.g. dex, JAR, .so files) from a source other than Google Play.

If necessary, you can consult your SDK provider(s) for further information.
```
i think that it's caused by  the used package "http_auth"

**Comment by Mixpeal** [comment]
The issue was with the webview package, i've already fixed this, try upgrading to latest version
